version: '3'
services:
  ipfs:
    image: ipfs/kubo:${VERSION_IPFS}
    volumes:
      - ipfs:/data/ipfs
    restart: unless-stopped
    network_mode: host
    command:
      - daemon
      - --migrate=true
      - --enable-pubsub-experiment
      - --agent-version-suffix=docker

  challenger:
    image: ${IMAGE_STATE_READER}:${VERSION_STATE_READER}
    env_file: .env
    volumes:
      - ipfs:/home/node/.ipfs
      - ./challenger.config.json:${APP_CONFIG_JSON}
      - ./private-key:${PRIVATE_KEY_FILE}
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    depends_on:
      - ipfs
      - mongodb
    network_mode: host

# Spin up the ipfs-daemon app first
volumes:
  ipfs:
    name: ipfs_daemon
