version: '3'
services:
  mongodb:
    image: mongo:5.0.4
    container_name: mongodb-challenger
    volumes:
      - database-challenger:/data/db
    env_file:
      - .env
    environment:
      - PUID=${GLOBAL_UID:-1000}
      - PGID=$(GLOBAL_GID:-1000)
    restart: unless-stopped
    command: --quiet --logpath /dev/null

volumes:
  database-challenger:
