version: '3'
services:
  ipfs:
    image: ipfs/kubo:${VERSION_IPFS}
    ports:
      - ${HOST_IPFS_PORT}:4001
    restart: unless-stopped
    command:
      - daemon
      - --migrate=true
      - --enable-pubsub-experiment
      - --agent-version-suffix=docker
      - --init-profile=server # avoids port scanning

  challenger:
    image: ${IMAGE_STATE_READER}:${VERSION_STATE_READER}
    env_file: .env
    volumes:
      - ./challenger.config.json:${APP_CONFIG_JSON}
      - ./private-key:${PRIVATE_KEY_FILE}
      - ./logs:/usr/src/app/logs
    restart: unless-stopped
    depends_on:
      - ipfs
      - mongodb
