version: '3'
services:
  mongodb:
    image: mongo:5.0.4
    container_name: mongodb-relayer
    volumes:
      - database:/data/db
    env_file:
      - .env
    environment:
      - PUID=${GLOBAL_UID:-1000}
      - PGID=$(GLOBAL_GID:-1000)
    restart: unless-stopped
    command:
      - --quiet
      - --logpath /dev/null
      - --bind_ip 127.0.0.1 # prevent connections from the internet

volumes:
  database:
