name: CI
on:
  pull_request:
    branches: ['master']

jobs:
  nx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'master'
      - run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      # The find is needed because ethers & docopt create the node_modules
      # folder inside the project, which interfere with the deps
      # defined at the root's node_modules folder.
      - run: |
          find packages -maxdepth 2 -name node_modules -exec rm -rf '{}' \;
          npx nx affected --target=test --configuration=ci
      - run: npx nx affected --target=docker-build
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: $(find . -name *Dockerfile | tr '\n' ' ')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
